/* Generated by the Nim Compiler v2.2.8 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217753 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217749.base = NTI33555184;
var NNI134217753 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217753.node = NNI134217753;
NTI134217753.base = NTI33555184;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557360 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2908(ti_p2))) {
      result_33557360 = src_p1;
      }
      else {
        result_33557360 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557360 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557360 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557360 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557360 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557360, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557360 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557360 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557360 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557360[i] = nimCopy(result_33557360[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557360 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557360 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557360[i] = nimCopy(result_33557360[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557360 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557360 = src_p1;
      break;
    }

  return result_33557360;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557473 = false;

  BeforeRet: {
    var x_33557474 = obj_p0;
    if ((x_33557474 == subclass_p1)) {
    result_33557473 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557474 == subclass_p1))) break Label2;
          if ((x_33557474 == null)) {
          result_33557473 = false;
          break BeforeRet;
          }
          
          x_33557474 = x_33557474.base;
        }
    };
    result_33557473 = true;
    break BeforeRet;
  };

  return result_33557473;

}

function toJSStr(s_p0) {
  var result_33556949 = null;

    var res_33557003 = newSeq__system_u2546((s_p0).length);
    var i_33557004 = 0;
    var j_33557005 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557004 < (s_p0).length)) break Label2;
          var c_33557006 = s_p0[i_33557004];
          if ((c_33557006 < 128)) {
          res_33557003[j_33557005] = String.fromCharCode(c_33557006);
          i_33557004 += 1;
          }
          else {
            var helper_33557032 = newSeq__system_u2546(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557033 = c_33557006.toString(16);
                  if ((((code_33557033) == null ? 0 : (code_33557033).length) == 1)) {
                  helper_33557032.push("%0");;
                  }
                  else {
                  helper_33557032.push("%");;
                  }
                  
                  helper_33557032.push(code_33557033);;
                  i_33557004 += 1;
                  if ((((s_p0).length <= i_33557004) || (s_p0[i_33557004] < 128))) {
                  break Label3;
                  }
                  
                  c_33557006 = s_p0[i_33557004];
                }
            };
++excHandler;
            try {
            res_33557003[j_33557005] = decodeURIComponent(helper_33557032.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557003[j_33557005] = helper_33557032.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557005 += 1;
        }
    };
    if (res_33557003.length < j_33557005) { for (var i = res_33557003.length ; i < j_33557005 ; ++i) res_33557003.push(null); }
               else { res_33557003.length = j_33557005; };
    result_33556949 = res_33557003.join("");

  return result_33556949;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557395 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557395 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557395;

}

function reraiseException() {
    if ((lastJSError == null)) {
    raiseException({message: [110,111,32,101,120,99,101,112,116,105,111,110,32,116,111,32,114,101,114,97,105,115,101], parent: null, m_type: NTI134217753, name: null, trace: [], up: null}, "ReraiseDefect");
    }
    else {
      if ((excHandler == 0)) {
      if (isNimException__system_u2043()) {
      unhandledException(lastJSError);
      }
      
      }
      
      throw lastJSError;
    }
    

  
}
var objectID_822083762 = [0];

function isFatPointer__system_u2908(ti_p0) {
  var result_33557342 = false;

  BeforeRet: {
    result_33557342 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557342;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_587202895 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_587202895 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_587202895;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_587202895 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_402653200 = [[]];

    result_402653200[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_402653200, 0, xHEX60gensym0_p0);

  return result_402653200[0];

}

function add__system_u1972(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2546(len_p0) {
  var result_33556982 = [];

    result_33556982 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556982[i] = null; }
  return result_33556982;

}

function isNimException__system_u2043() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556478 = null;

    if (isNimException__system_u2043()) {
    result_33556478 = lastJSError;
    }
    

  return result_33556478;

}

function raiseDefect() {
    if (isNimException__system_u2043()) {
    var e_33556694 = getCurrentException();
    if (isObj(e_33556694.m_type, NTI33555184)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556694);
    }
    
    throw e_33556694;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556688 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556688[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556688[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556688[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556688[0], [32,91]);;
    add__system_u1972(buf_33556688, 0, e_p0.name);
    nimAddStrStr(buf_33556688[0], [93,10]);;
    var cbuf_33556689 = toJSStr(buf_33556688[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556689);
  }
  else {
    throw cbuf_33556689;
  }
  

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}
async function handleRequest__client_u49(el_p0, methodStr_p1, url_p2) {
  var result_587202614 = null;

  BeforeRet: {
    var targetSel_587202620 = el_p0.getAttribute("crown-target");
    var swap_587202621 = el_p0.getAttribute("crown-swap");
    if (((swap_587202621 == null) || (swap_587202621 == ""))) {
    swap_587202621 = "innerHTML";
    }
    
    el_p0.classList.add("crown-loading");
    var options_587202622 = {};
    options_587202622.method = methodStr_p1;
    if (((methodStr_p1 == "POST") && (el_p0.nodeName == "FORM"))) {
    options_587202622.body = new FormData(el_p0);
    }
    
++excHandler;
    try {
    var res_587202652 = (await fetch(url_p2, options_587202622));
    var txt_587202657 = (await res_587202652.text());
    if ((!((targetSel_587202620 == null)) && !((targetSel_587202620 == "")))) {
    var targetNodes_587202658 = document.querySelectorAll(targetSel_587202620);
    if ((0 < (targetNodes_587202658).length)) {
    var target_587202666 = targetNodes_587202658[chckIndx(0, 0, (targetNodes_587202658).length - 1)];
    if ((swap_587202621 == "innerHTML")) {
    target_587202666.innerHTML = txt_587202657;
    }
    else {
    if ((swap_587202621 == "outerHTML")) {
    target_587202666.outerHTML = txt_587202657;
    }
    }
    }
    
    }
    
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
    if (lastJSError && (lastJSError instanceof Error)) {
    var err_587202667 = lastJSError;
    console.error(("Crown API Error:"), (err_587202667));
    }
    else {
    	reraiseException();
    }
    lastJSError = prevJSError;
    } finally {
    el_p0.classList.remove("crown-loading");
    }
    result_587202614 = undefined;
    break BeforeRet;
  };

  return result_587202614;

}
var Temporary1;

function HEX3Aanonymous__client_u241(e_p0) {
    var Temporary1;

function HEX3Aanonymous__client_u243(e_p0) {
    var Temporary1;
    var Temporary2;

  BeforeRet: {
    var target_587202805 = e_p0.target;
    var el_587202806 = target_587202805.closest("[crown-get], [crown-post]");
    if (!((el_587202806 == null))) {
    if ((el_587202806.nodeName == "FORM")) {
    break BeforeRet;
    }
    
    var inputEl_587202811 = el_587202806;
    if ((((el_587202806.nodeName == "BUTTON") && (inputEl_587202811.type == "submit")) && !((inputEl_587202811.form == null)))) {
    break BeforeRet;
    }
    
    e_p0.preventDefault();
    if (el_587202806.hasAttribute("crown-get")) {
    Temporary1 = "GET";
    }
    else {
    Temporary1 = "POST";
    }
    
    var methodStr_587202816 = Temporary1;
    if (el_587202806.hasAttribute("crown-get")) {
    Temporary2 = el_587202806.getAttribute("crown-get");
    }
    else {
    Temporary2 = el_587202806.getAttribute("crown-post");
    }
    
    var url_587202817 = Temporary2;
    (handleRequest__client_u49(el_587202806, methodStr_587202816, url_587202817));
    }
    
  };

  
}
    var Temporary2;

function HEX3Aanonymous__client_u274(e_p0) {
    var Temporary1;
    var Temporary2;

    var target_587202836 = e_p0.target;
    var form_587202837 = target_587202836.closest("[crown-get], [crown-post]");
    if (!((form_587202837 == null))) {
    e_p0.preventDefault();
    if (form_587202837.hasAttribute("crown-post")) {
    Temporary1 = "POST";
    }
    else {
    Temporary1 = "GET";
    }
    
    var methodStr_587202842 = Temporary1;
    if (form_587202837.hasAttribute("crown-get")) {
    Temporary2 = form_587202837.getAttribute("crown-get");
    }
    else {
    Temporary2 = form_587202837.getAttribute("crown-post");
    }
    
    var url_587202843 = Temporary2;
    (handleRequest__client_u49(form_587202837, methodStr_587202842, url_587202843));
    }
    

  
}

    Temporary1 = HEX3Aanonymous__client_u243.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__client_u243; Temporary1.ClE_0 = null;
    document.addEventListener("click", Temporary1, false);
    Temporary2 = HEX3Aanonymous__client_u274.bind(null); Temporary2.ClP_0 = HEX3Aanonymous__client_u274; Temporary2.ClE_0 = null;
    document.addEventListener("submit", Temporary2, false);

  
}
Temporary1 = HEX3Aanonymous__client_u241.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__client_u241; Temporary1.ClE_0 = null;
document.addEventListener("DOMContentLoaded", Temporary1, false);
